-- =============================================================================
-- Harmony Suite — demo data
--
-- Run this AFTER `supabase db reset` when you want a populated system to
-- present from:
--
--   supabase db reset
--   docker exec -i supabase_db_harmony-suite psql -U postgres -d postgres \
--     < supabase/demo-seed.sql
--
-- Deliberately NOT in seed.sql: a fresh checkout should start clean. This is
-- the "ready to present" overlay on top of it.
--
-- It stages one applicant at every point of the recruitment pipeline so each
-- module has something to show without clicking through the whole flow first,
-- and gives the payroll/leave/attendance modules real data to compute from.
-- =============================================================================

-- ---- Job postings -----------------------------------------------------------
insert into public.job_postings (id, department_id, position_id, description, requirements, employment_type, vacancies, status, posted_by, date_posted, closing_date) values
  ('c1000000-0000-0000-0000-000000000001', 'd0000000-0000-0000-0000-000000000002', 'e0000000-0000-0000-0000-000000000002',
   'Drive retail sales, build customer relationships, and hit monthly targets in a fast-paced store environment.',
   'At least 1 year retail or customer-facing experience. Strong communication skills. Willing to work weekends.',
   'regular', 3, 'open', 'a0000000-0000-0000-0000-000000000001', now() - interval '14 days', current_date + 30),
  ('c1000000-0000-0000-0000-000000000002', 'd0000000-0000-0000-0000-000000000003', 'e0000000-0000-0000-0000-000000000004',
   'Provide first-line technical support to staff across all branches, maintain hardware inventory, and escalate systems issues.',
   'IT-related degree or equivalent experience. Familiarity with Windows and basic networking.',
   'regular', 1, 'open', 'a0000000-0000-0000-0000-000000000001', now() - interval '7 days', current_date + 21),
  ('c1000000-0000-0000-0000-000000000003', 'd0000000-0000-0000-0000-000000000001', 'e0000000-0000-0000-0000-000000000001',
   'Support recruitment, onboarding, and employee records for a growing team.',
   'HR or Psychology graduate. Detail-oriented. Familiar with basic labor standards.',
   'regular', 1, 'closed', 'a0000000-0000-0000-0000-000000000001', now() - interval '40 days', current_date - 5)
on conflict do nothing;

-- ---- Applicants -------------------------------------------------------------
insert into public.applicants (id, first_name, middle_name, last_name, email, phone, address, resume_url, cover_letter) values
  ('c2000000-0000-0000-0000-000000000001', 'Andrea', 'Reyes',   'Santos',    'andrea.santos@example.com',   '09171000001', '12 Mabini St, Makati City',      'demo/resume-andrea.pdf',  'I am excited to bring my retail experience to your team.'),
  ('c2000000-0000-0000-0000-000000000002', 'Marco',  'Lim',     'Villanueva','marco.villanueva@example.com','09171000002', '88 Rizal Ave, Quezon City',      'demo/resume-marco.pdf',   'Five years of frontline sales experience.'),
  ('c2000000-0000-0000-0000-000000000003', 'Bea',    'Cruz',    'Manalo',    'bea.manalo@example.com',      '09171000003', '5 Bonifacio Rd, Pasig City',     'demo/resume-bea.pdf',     'I would love to grow my IT support career here.'),
  ('c2000000-0000-0000-0000-000000000004', 'Paolo',  'Garcia',  'Del Rosario','paolo.delrosario@example.com','09171000004','21 Katipunan Ave, Quezon City',  'demo/resume-paolo.pdf',   'Detail-oriented and eager to contribute.'),
  ('c2000000-0000-0000-0000-000000000005', 'Nina',   'Torres',  'Aquino',    'nina.aquino@example.com',     '09171000005', '9 Aguinaldo Hwy, Dasmarinas',    'demo/resume-nina.pdf',    'Ready to start immediately.'),
  ('c2000000-0000-0000-0000-000000000006', 'Rafael', 'Mendoza', 'Bautista',  'rafael.bautista@example.com', '09171000006', '77 Ortigas Ave, Pasig City',     'demo/resume-rafael.pdf',  'Looking for a long-term role in sales.')
on conflict do nothing;

-- ---- Applications, one per pipeline stage -----------------------------------
-- reference_code is generated by the column default (APP-YYYY-NNNN).
insert into public.applications (id, applicant_id, job_posting_id, status, created_at) values
  -- 1. brand new, waiting to be screened  -> Recruitment
  ('c3000000-0000-0000-0000-000000000001', 'c2000000-0000-0000-0000-000000000001', 'c1000000-0000-0000-0000-000000000001', 'submitted', now() - interval '2 days'),
  ('c3000000-0000-0000-0000-000000000006', 'c2000000-0000-0000-0000-000000000006', 'c1000000-0000-0000-0000-000000000001', 'submitted', now() - interval '1 day'),
  -- 2. qualified, waiting for an interview -> Interview Management
  ('c3000000-0000-0000-0000-000000000002', 'c2000000-0000-0000-0000-000000000002', 'c1000000-0000-0000-0000-000000000001', 'qualified', now() - interval '6 days'),
  -- 3. initial interview scheduled         -> Interview Management
  ('c3000000-0000-0000-0000-000000000003', 'c2000000-0000-0000-0000-000000000003', 'c1000000-0000-0000-0000-000000000002', 'interview_scheduled', now() - interval '8 days'),
  -- 4. hired, waiting for a job offer      -> Deployment
  ('c3000000-0000-0000-0000-000000000004', 'c2000000-0000-0000-0000-000000000004', 'c1000000-0000-0000-0000-000000000001', 'hired', now() - interval '12 days'),
  -- 5. offer sent, waiting on the applicant -> Deployment + /track portal
  ('c3000000-0000-0000-0000-000000000005', 'c2000000-0000-0000-0000-000000000005', 'c1000000-0000-0000-0000-000000000001', 'offered', now() - interval '15 days')
on conflict do nothing;

update public.applications set reviewed_by = 'a0000000-0000-0000-0000-000000000003', reviewed_at = now() - interval '5 days'
where id in ('c3000000-0000-0000-0000-000000000002','c3000000-0000-0000-0000-000000000003',
             'c3000000-0000-0000-0000-000000000004','c3000000-0000-0000-0000-000000000005');

insert into public.application_history (application_id, event, actor_id, created_at)
select id, 'submitted', null, created_at from public.applications where id::text like 'c3000000%'
on conflict do nothing;

-- ---- Interviews -------------------------------------------------------------
-- Bea: initial interview scheduled, run by HR Staff (Sam).
insert into public.interviews (id, application_id, interview_type, scheduled_at, interviewer_id, mode, meeting_link, status, remarks) values
  ('c4000000-0000-0000-0000-000000000001', 'c3000000-0000-0000-0000-000000000003', 'initial',
   date_trunc('hour', now()) + interval '1 day 2 hours', 'a0000000-0000-0000-0000-000000000003',
   'online', 'https://meet.example.com/harmony-bea-initial', 'scheduled', 'Screening call for IT Support.')
on conflict do nothing;

-- Paolo: passed initial (run by Sam), handed off to Maria for the final round.
insert into public.interviews (id, application_id, interview_type, scheduled_at, interviewer_id, mode, location, status,
  rating_communication, rating_technical_skills, rating_confidence, rating_experience, rating_problem_solving,
  overall_impression, interview_notes) values
  ('c4000000-0000-0000-0000-000000000002', 'c3000000-0000-0000-0000-000000000004', 'initial',
   now() - interval '9 days', 'a0000000-0000-0000-0000-000000000003', 'face_to_face', 'Main Office - Meeting Room 2', 'passed',
   4, 4, 5, 4, 4, 'Strong communicator, clear retail background, good cultural fit.', 'Recommend advancing to final interview.')
on conflict do nothing;

insert into public.interviews (id, application_id, interview_type, scheduled_at, interviewer_id, mode, location, status,
  rating_technical_evaluation, rating_culture_fit, rating_leadership, final_remarks) values
  ('c4000000-0000-0000-0000-000000000003', 'c3000000-0000-0000-0000-000000000004', 'final',
   now() - interval '6 days', 'a0000000-0000-0000-0000-000000000002', 'face_to_face', 'Main Office - Meeting Room 1', 'passed',
   4, 5, 4, 'Excellent fit. Approved for hiring.')
on conflict do nothing;

update public.applications set final_interviewer_id = 'a0000000-0000-0000-0000-000000000002'
where id in ('c3000000-0000-0000-0000-000000000004','c3000000-0000-0000-0000-000000000005');

-- Nina: full interview history, already through to an offer.
insert into public.interviews (id, application_id, interview_type, scheduled_at, interviewer_id, mode, location, status,
  rating_communication, rating_technical_skills, rating_confidence, rating_experience, rating_problem_solving, overall_impression) values
  ('c4000000-0000-0000-0000-000000000004', 'c3000000-0000-0000-0000-000000000005', 'initial',
   now() - interval '13 days', 'a0000000-0000-0000-0000-000000000003', 'face_to_face', 'Main Office - Meeting Room 2', 'passed',
   5, 4, 4, 5, 4, 'Very strong candidate, immediately available.')
on conflict do nothing;
insert into public.interviews (id, application_id, interview_type, scheduled_at, interviewer_id, mode, location, status,
  rating_technical_evaluation, rating_culture_fit, rating_leadership, final_remarks) values
  ('c4000000-0000-0000-0000-000000000005', 'c3000000-0000-0000-0000-000000000005', 'final',
   now() - interval '11 days', 'a0000000-0000-0000-0000-000000000002', 'face_to_face', 'Main Office - Meeting Room 1', 'passed',
   5, 5, 4, 'Hire. Best candidate in this batch.')
on conflict do nothing;

-- ---- Job offer for Nina (pending — she can accept it from /track) -----------
insert into public.job_offers (id, application_id, employment_type, salary_grade_id, proposed_salary, currency,
  work_schedule_id, working_hours, working_days, start_date, additional_compensation, prepared_by, status, offer_date)
select 'c5000000-0000-0000-0000-000000000001', 'c3000000-0000-0000-0000-000000000005', 'regular',
  'f0000000-0000-0000-0000-000000000002', 24000, 'PHP',
  ws.id, '8:00 AM - 5:00 PM', 'Mon, Tue, Wed, Thu, Fri',
  current_date + 14, 'Transportation allowance of PHP 2,000/month.',
  'a0000000-0000-0000-0000-000000000003', 'pending', current_date - 3
from public.work_schedules ws where ws.is_default limit 1
on conflict do nothing;

-- ---- Employees --------------------------------------------------------------
-- Three active employees so Attendance, Leave, and Payroll all have subjects.
insert into public.employees (id, first_name, middle_name, last_name, email, phone, address, province, city, barangay,
  birth_date, gender,
  civil_status, nationality, department_id, position_id, salary_grade_id, basic_salary, currency,
  employment_type, employment_status, hire_date, work_schedule_id)
select v.id::uuid, v.fn, v.mn, v.ln, v.email, v.phone, v.addr, v.province, v.city, v.barangay,
  v.bd::date, v.gender, v.civil, 'Filipino',
  v.dept::uuid, v.pos::uuid, v.grade::uuid, v.salary, 'PHP', ws.employment_type, v.status::employment_status,
  v.hired::date, ws.id
from (values
  -- Each on a different shift so the roster shows real variety, including one
  -- overnight worker.
  ('c6000000-0000-0000-0000-000000000001','Liza','Domingo','Fernandez','liza.fernandez@example.com','09181000001','14 Malakas St','Metro Manila','Quezon City','Kamuning','1994-03-12','Female','Single','d0000000-0000-0000-0000-000000000002','e0000000-0000-0000-0000-000000000002','f0000000-0000-0000-0000-000000000002',24000,'active', (current_date - interval '2 years')::text, 'a1000000-0000-0000-0000-000000000001'),
  ('c6000000-0000-0000-0000-000000000002','Jerome','Sy','Castillo','jerome.castillo@example.com','09181000002','3 Sampaguita St','Metro Manila','Pasig','Kapitolyo','1990-11-02','Male','Married','d0000000-0000-0000-0000-000000000003','e0000000-0000-0000-0000-000000000004','f0000000-0000-0000-0000-000000000003',32000,'active', (current_date - interval '3 years')::text, 'a1000000-0000-0000-0000-000000000002'),
  ('c6000000-0000-0000-0000-000000000003','Grace','Ann','Peralta','grace.peralta@example.com','09181000003','40 Ilang-Ilang St','Metro Manila','Makati','Poblacion','1998-06-25','Female','Single','d0000000-0000-0000-0000-000000000001','e0000000-0000-0000-0000-000000000001','f0000000-0000-0000-0000-000000000001',18000,'active', (current_date - interval '8 months')::text, 'a1000000-0000-0000-0000-000000000003'),
  ('c6000000-0000-0000-0000-000000000004','Pia','Marie','Reyes','pia.reyes@example.com','09181000004','22 Mabini St','Metro Manila','Manila','Ermita','2001-09-08','Female','Single','d0000000-0000-0000-0000-000000000001','e0000000-0000-0000-0000-000000000001',(select id from public.salary_grades where employment_type = 'part_time' order by min_salary limit 1)::text,8000,'active', (current_date - interval '4 months')::text, 'Part-Time Morning')
) as v(id, fn, mn, ln, email, phone, addr, province, city, barangay, bd, gender, civil, dept, pos, grade, salary, status, hired, sched)
-- Resolves the shift from the row, which names it either by id (the seeded
-- full-time shifts) or by name (the part-time ones, whose ids the migration
-- generates). employment_type comes from the shift itself, so an employee can
-- never be seeded onto an incompatible one.
cross join lateral (
  select s.id, s.employment_type
  from public.work_schedules s
  where s.id::text = v.sched or s.name = v.sched
  limit 1
) ws
on conflict do nothing;

-- ---- Employee logins --------------------------------------------------------
-- Same fixed default password the app itself assigns (Employee123), so the
-- Employee Portal can be demoed. handle_new_user() creates each profiles row;
-- the update below turns it into a linked employee account.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token
)
select '00000000-0000-0000-0000-000000000000', v.uid::uuid, 'authenticated', 'authenticated',
  v.email, crypt('Employee123', gen_salt('bf')), now(), now(),
  '{"provider":"email","providers":["email"]}', jsonb_build_object('full_name', v.full_name),
  now(), now(), '', '', '', ''
from (values
  ('c9000000-0000-0000-0000-000000000001', 'liza.fernandez@example.com',  'Liza Fernandez',  'c6000000-0000-0000-0000-000000000001'),
  ('c9000000-0000-0000-0000-000000000002', 'jerome.castillo@example.com', 'Jerome Castillo', 'c6000000-0000-0000-0000-000000000002')
) as v(uid, email, full_name, employee_id)
on conflict do nothing;

update public.profiles p
set full_name = v.full_name, role = 'employee', status = 'active',
    employee_id = v.employee_id::uuid, invited_at = now(), activated_at = now()
from (values
  ('c9000000-0000-0000-0000-000000000001', 'Liza Fernandez',  'c6000000-0000-0000-0000-000000000001'),
  ('c9000000-0000-0000-0000-000000000002', 'Jerome Castillo', 'c6000000-0000-0000-0000-000000000002')
) as v(uid, full_name, employee_id)
where p.id = v.uid::uuid;

-- ---- Attendance: the last 10 working days, with realistic variation ---------
-- Liza is punctual, Jerome runs a few minutes late twice, Grace has one absence
-- and one half day — enough for payroll to produce non-zero deductions.
-- Covers the whole current payroll period (1st of the month through
-- yesterday), not just a trailing window — otherwise every earlier working day
-- has no record and payroll correctly, but unhelpfully, bills it as an absence.
with workdays as (
  select gs::date as day, row_number() over (order by gs) as n
  from generate_series(date_trunc('month', current_date), current_date - interval '1 day', interval '1 day') gs
  where extract(dow from gs) between 1 and 5
),
-- Times come from each employee's own shift, so a recorded day always lines up
-- with the schedule it's measured against.
staff as (
  select e.id as employee_id, s.late_mins, ws.start_time, ws.end_time,
         (ws.end_time <= ws.start_time) as is_overnight,
         -- Paid hours in one shift: the span, rolled over midnight where the
         -- shift is overnight, less the unpaid break.
         (extract(epoch from (ws.end_time - ws.start_time))
            + case when ws.end_time <= ws.start_time then 86400 else 0 end) / 3600.0
           - ws.break_minutes / 60.0 as shift_hours
  from (values
    ('c6000000-0000-0000-0000-000000000001'::uuid, 0),   -- Liza: always on time
    ('c6000000-0000-0000-0000-000000000002'::uuid, 18),  -- Jerome: late on every 4th day
    ('c6000000-0000-0000-0000-000000000003'::uuid, 25),  -- Grace: late, plus an absence and a half day
    ('c6000000-0000-0000-0000-000000000004'::uuid, 0)    -- Pia: part-time, always on time
  ) as s(employee_id, late_mins)
  join public.employees e on e.id = s.employee_id
  join public.work_schedules ws on ws.id = e.work_schedule_id
),
plan as (
  select
    s.employee_id,
    w.day,
    s.start_time,
    s.end_time,
    s.is_overnight,
    s.shift_hours,
    -- Grace (3rd employee) is absent on day 3 and works a half day on day 5.
    case
      when s.employee_id = 'c6000000-0000-0000-0000-000000000003'::uuid and w.n = 3 then 'absent'
      when s.employee_id = 'c6000000-0000-0000-0000-000000000003'::uuid and w.n = 5 then 'half_day'
      when s.late_mins > 0 and w.n % 4 = 1 then 'late'
      else 'present'
    end as status,
    case when s.late_mins > 0 and w.n % 4 = 1 then s.late_mins else 0 end as late_mins
  from staff s cross join workdays w
)
insert into public.attendance_records
  (employee_id, attendance_date, time_in, time_out, working_hours, late_minutes, undertime_minutes, overtime_minutes, status)
select
  p.employee_id,
  p.day,
  -- AT TIME ZONE 'Asia/Manila' reads the wall-clock time AS Manila time.
  -- A plain ::timestamptz cast would read it as UTC, which is why an 8:00 AM
  -- shift previously displayed as 4:00 PM in a UTC+8 browser.
  case when p.status = 'absent' then null
       else ((p.day + p.start_time + make_interval(mins => p.late_mins)) at time zone 'Asia/Manila') end,
  case when p.status = 'absent' then null
       -- Half day: out 4 hours after starting.
       when p.status = 'half_day' then ((p.day + p.start_time + interval '4 hours') at time zone 'Asia/Manila')
       -- A shift ending at or before it starts runs past midnight, so its end
       -- lands on the next calendar day.
       else ((p.day + p.end_time + case when p.is_overnight then interval '1 day' else interval '0' end)
             at time zone 'Asia/Manila') end,
  case when p.status = 'absent' then 0
       when p.status = 'half_day' then p.shift_hours / 2
       else p.shift_hours end,
  p.late_mins,
  case when p.status = 'half_day' then round(p.shift_hours * 30) else 0 end,
  0,
  p.status::attendance_status
from plan p
on conflict (employee_id, attendance_date) do nothing;

-- ---- Leave ------------------------------------------------------------------
-- Balances for everyone, then one pending request (for the HR Manager to
-- approve live during the demo) and one already-approved request.
-- remaining_credits is a generated column — it derives from total/used.
insert into public.leave_balances (employee_id, leave_type_id, total_credits, used_credits, year)
select e.id, lt.id, lt.default_credits, 0, extract(year from current_date)::int
from public.employees e cross join public.leave_types lt
where e.id::text like 'c6000000%'
on conflict do nothing;

insert into public.leave_requests (id, employee_id, leave_type_id, start_date, end_date, days_requested, reason, status, created_at)
select 'c7000000-0000-0000-0000-000000000001', 'c6000000-0000-0000-0000-000000000001', lt.id,
  current_date + 5, current_date + 6, 2, 'Family matters — out of town.', 'pending', now() - interval '1 day'
from public.leave_types lt where lt.name ilike '%vacation%' limit 1
on conflict do nothing;

insert into public.leave_requests (id, employee_id, leave_type_id, start_date, end_date, days_requested, reason, status,
  reviewed_by, reviewed_at, created_at)
select 'c7000000-0000-0000-0000-000000000002', 'c6000000-0000-0000-0000-000000000002', lt.id,
  current_date - 20, current_date - 20, 1, 'Medical check-up.', 'approved',
  'a0000000-0000-0000-0000-000000000002', now() - interval '22 days', now() - interval '25 days'
from public.leave_types lt where lt.name ilike '%sick%' limit 1
on conflict do nothing;

-- ---- Payroll: a draft period ready for the HR Manager to review & release ---
insert into public.payroll_periods (id, period_start, period_end, pay_date, frequency, status, created_by)
values ('c8000000-0000-0000-0000-000000000001',
        date_trunc('month', current_date)::date,
        (date_trunc('month', current_date) + interval '1 month - 1 day')::date,
        (date_trunc('month', current_date) + interval '1 month + 4 days')::date,
        'monthly', 'draft', 'a0000000-0000-0000-0000-000000000003')
on conflict do nothing;

-- ---- Change requests: one pending, so Approvals isn't empty -----------------
insert into public.change_requests (target_table, operation, payload, summary, status, requested_by, requested_at)
-- Explicit casts: pulling the rows through a subselect loses the enum
-- inference an INSERT ... VALUES would otherwise get from the target columns.
select v.target_table,
       v.operation::change_request_operation,
       v.payload,
       v.summary,
       v.status::change_request_status,
       v.requested_by::uuid,
       v.requested_at
from (values
  ('departments', 'create',
   '{"name":"Logistics","description":"Fleet, delivery, and warehouse operations"}'::jsonb,
   'Create department: Logistics', 'pending', 'a0000000-0000-0000-0000-000000000003', now() - interval '3 hours'),
  ('positions', 'create',
   ('{"title":"Delivery Driver","description":"Operates company vehicles for scheduled deliveries","department_id":"'
     || 'd0000000-0000-0000-0000-000000000004' || '"}')::jsonb,
   'Create position: Delivery Driver', 'pending', 'a0000000-0000-0000-0000-000000000003', now() - interval '1 hour')
) as v(target_table, operation, payload, summary, status, requested_by, requested_at)
where not exists (select 1 from public.change_requests cr where cr.summary = v.summary);

-- ---- Summary ----------------------------------------------------------------
do $$
declare
  v_apps int; v_emps int; v_att int; v_leave int; v_cr int;
begin
  select count(*) into v_apps from public.applications;
  select count(*) into v_emps from public.employees;
  select count(*) into v_att from public.attendance_records;
  select count(*) into v_leave from public.leave_requests;
  select count(*) into v_cr from public.change_requests where status = 'pending';
  raise notice 'Demo data loaded: % applications, % employees, % attendance records, % leave requests, % pending approvals',
    v_apps, v_emps, v_att, v_leave, v_cr;
end $$;
