-- Generated by scratchpad/gen-locations.cjs — see the migration header for scope.
-- Provinces, plus Metro Manila. Regions are otherwise not modelled: an address needs
-- province, city, and barangay, and adding a fourth level would be one more
-- dropdown for no gain.
insert into public.ph_locations (level, name) values
  ('province', 'Abra'),
  ('province', 'Agusan del Norte'),
  ('province', 'Agusan del Sur'),
  ('province', 'Aklan'),
  ('province', 'Albay'),
  ('province', 'Antique'),
  ('province', 'Apayao'),
  ('province', 'Aurora'),
  ('province', 'Basilan'),
  ('province', 'Bataan'),
  ('province', 'Batanes'),
  ('province', 'Batangas'),
  ('province', 'Benguet'),
  ('province', 'Biliran'),
  ('province', 'Bohol'),
  ('province', 'Bukidnon'),
  ('province', 'Bulacan'),
  ('province', 'Cagayan'),
  ('province', 'Camarines Norte'),
  ('province', 'Camarines Sur'),
  ('province', 'Camiguin'),
  ('province', 'Capiz'),
  ('province', 'Catanduanes'),
  ('province', 'Cavite'),
  ('province', 'Cebu'),
  ('province', 'Cotabato'),
  ('province', 'Davao de Oro'),
  ('province', 'Davao del Norte'),
  ('province', 'Davao del Sur'),
  ('province', 'Davao Occidental'),
  ('province', 'Davao Oriental'),
  ('province', 'Dinagat Islands'),
  ('province', 'Eastern Samar'),
  ('province', 'Guimaras'),
  ('province', 'Ifugao'),
  ('province', 'Ilocos Norte'),
  ('province', 'Ilocos Sur'),
  ('province', 'Iloilo'),
  ('province', 'Isabela'),
  ('province', 'Kalinga'),
  ('province', 'La Union'),
  ('province', 'Laguna'),
  ('province', 'Lanao del Norte'),
  ('province', 'Lanao del Sur'),
  ('province', 'Leyte'),
  ('province', 'Maguindanao del Norte'),
  ('province', 'Maguindanao del Sur'),
  ('province', 'Marinduque'),
  ('province', 'Masbate'),
  ('province', 'Metro Manila'),
  ('province', 'Misamis Occidental'),
  ('province', 'Misamis Oriental'),
  ('province', 'Mountain Province'),
  ('province', 'Negros Occidental'),
  ('province', 'Negros Oriental'),
  ('province', 'Northern Samar'),
  ('province', 'Nueva Ecija'),
  ('province', 'Nueva Vizcaya'),
  ('province', 'Occidental Mindoro'),
  ('province', 'Oriental Mindoro'),
  ('province', 'Palawan'),
  ('province', 'Pampanga'),
  ('province', 'Pangasinan'),
  ('province', 'Quezon'),
  ('province', 'Quirino'),
  ('province', 'Rizal'),
  ('province', 'Romblon'),
  ('province', 'Samar'),
  ('province', 'Sarangani'),
  ('province', 'Siquijor'),
  ('province', 'Sorsogon'),
  ('province', 'South Cotabato'),
  ('province', 'Southern Leyte'),
  ('province', 'Sultan Kudarat'),
  ('province', 'Sulu'),
  ('province', 'Surigao del Norte'),
  ('province', 'Surigao del Sur'),
  ('province', 'Tarlac'),
  ('province', 'Tawi-Tawi'),
  ('province', 'Zambales'),
  ('province', 'Zamboanga del Norte'),
  ('province', 'Zamboanga del Sur'),
  ('province', 'Zamboanga Sibugay')
on conflict do nothing;

-- Metro Manila: cities and municipalities
insert into public.ph_locations (parent_id, level, name)
select p.id, 'city', v.name from public.ph_locations p
cross join (values
  ('Caloocan'),
  ('Las Piñas'),
  ('Makati'),
  ('Malabon'),
  ('Mandaluyong'),
  ('Manila'),
  ('Marikina'),
  ('Muntinlupa'),
  ('Navotas'),
  ('Parañaque'),
  ('Pasay'),
  ('Pasig'),
  ('Pateros'),
  ('Quezon City'),
  ('San Juan'),
  ('Taguig'),
  ('Valenzuela')
) as v(name)
where p.level = 'province' and p.name = 'Metro Manila'
on conflict do nothing;

-- Cavite: cities and municipalities
insert into public.ph_locations (parent_id, level, name)
select p.id, 'city', v.name from public.ph_locations p
cross join (values
  ('Bacoor'),
  ('Carmona'),
  ('Cavite City'),
  ('Dasmariñas'),
  ('General Trias'),
  ('Imus'),
  ('Kawit'),
  ('Noveleta'),
  ('Rosario'),
  ('Silang'),
  ('Tagaytay'),
  ('Trece Martires')
) as v(name)
where p.level = 'province' and p.name = 'Cavite'
on conflict do nothing;

-- Quezon City: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Bagumbayan'),
  ('Batasan Hills'),
  ('Commonwealth'),
  ('Diliman'),
  ('Fairview'),
  ('Holy Spirit'),
  ('Kamuning'),
  ('Novaliches'),
  ('Payatas'),
  ('Project 6'),
  ('San Antonio'),
  ('Tandang Sora')
) as v(name)
where c.level = 'city' and c.name = 'Quezon City'
on conflict do nothing;

-- Pasig: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Bagong Ilog'),
  ('Caniogan'),
  ('Kapitolyo'),
  ('Manggahan'),
  ('Oranbo'),
  ('Pinagbuhatan'),
  ('San Antonio'),
  ('Santolan'),
  ('Ugong')
) as v(name)
where c.level = 'city' and c.name = 'Pasig'
on conflict do nothing;

-- Makati: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Bangkal'),
  ('Bel-Air'),
  ('Guadalupe Nuevo'),
  ('Guadalupe Viejo'),
  ('Poblacion'),
  ('San Antonio'),
  ('San Lorenzo'),
  ('Pio del Pilar')
) as v(name)
where c.level = 'city' and c.name = 'Makati'
on conflict do nothing;

-- Manila: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Binondo'),
  ('Ermita'),
  ('Intramuros'),
  ('Malate'),
  ('Paco'),
  ('Pandacan'),
  ('Sampaloc'),
  ('San Miguel'),
  ('Santa Cruz'),
  ('Tondo')
) as v(name)
where c.level = 'city' and c.name = 'Manila'
on conflict do nothing;

-- Taguig: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Bagumbayan'),
  ('Bambang'),
  ('Fort Bonifacio'),
  ('Lower Bicutan'),
  ('Signal Village'),
  ('Ususan'),
  ('Western Bicutan')
) as v(name)
where c.level = 'city' and c.name = 'Taguig'
on conflict do nothing;

-- Dasmariñas: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Burol'),
  ('Paliparan I'),
  ('Paliparan II'),
  ('Salawag'),
  ('Sampaloc I'),
  ('San Agustin'),
  ('Zone I'),
  ('Zone IV')
) as v(name)
where c.level = 'city' and c.name = 'Dasmariñas'
on conflict do nothing;

-- Bacoor: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Aniban I'),
  ('Habay I'),
  ('Mambog I'),
  ('Molino I'),
  ('Niog I'),
  ('Real I'),
  ('Talaba I')
) as v(name)
where c.level = 'city' and c.name = 'Bacoor'
on conflict do nothing;

-- Imus: barangays
insert into public.ph_locations (parent_id, level, name)
select c.id, 'barangay', v.name from public.ph_locations c
cross join (values
  ('Alapan I-A'),
  ('Anabu I-A'),
  ('Bayan Luma I'),
  ('Bucandala I'),
  ('Malagasang I-A'),
  ('Poblacion I-A'),
  ('Tanzang Luma I')
) as v(name)
where c.level = 'city' and c.name = 'Imus'
on conflict do nothing;
