import * as React from 'react'
import { useNavigate } from 'react-router-dom'
import type { ColumnDef } from '@tanstack/react-table'
import { motion } from 'framer-motion'
import { FileBarChart, Users, Wallet, CalendarClock, CalendarCheck, Briefcase, Plus } from 'lucide-react'
import { DataTable } from '@/components/data-table'
import { Card, CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select'
import { useExportHistory, useReportDashboardStats, useReportsRealtimeAlerts } from '@/hooks/useReports'
import { REPORT_FORMAT_LABEL, REPORT_TYPE_LABEL, ALL_FILTER, type ReportType } from '@/lib/reportTypes'
import type { ReportFormat } from '@/lib/database.types'

function StatCard({
  label,
  value,
  icon: Icon,
  isLoading,
  index,
}: {
  label: string
  value: number
  icon: React.ComponentType<{ className?: string }>
  isLoading: boolean
  index: number
}) {
  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3, delay: index * 0.05 }}>
      <Card>
        <CardContent className="flex items-center gap-3 p-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-accent/10 text-accent">
            <Icon className="h-4 w-4" />
          </div>
          <div>
            <p className="text-xs text-muted-foreground">{label}</p>
            {isLoading ? <Skeleton className="mt-1 h-6 w-12" /> : <p className="font-display text-xl font-bold text-foreground">{value}</p>}
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}

const FORMAT_VARIANT: Record<ReportFormat, 'secondary' | 'success' | 'outline'> = {
  pdf: 'outline',
  excel: 'success',
  docx: 'secondary',
}

interface ExportHistoryRow {
  id: string
  report_type: string
  format: ReportFormat
  created_at: string
  profiles: { full_name: string } | null
}

export default function ReportsPage() {
  useReportsRealtimeAlerts()
  const navigate = useNavigate()
  const { data: stats, isLoading: statsLoading } = useReportDashboardStats()
  const { data: history, isLoading: historyLoading } = useExportHistory()

  const [typeFilter, setTypeFilter] = React.useState<string>(ALL_FILTER)

  const rows = React.useMemo(() => {
    if (!history) return []
    return (history as ExportHistoryRow[]).filter((r) => typeFilter === ALL_FILTER || r.report_type === typeFilter)
  }, [history, typeFilter])

  const columns: ColumnDef<ExportHistoryRow>[] = [
    {
      id: '_searchText',
      accessorFn: (row) => [row.report_type, row.profiles?.full_name].filter(Boolean).join(' ').toLowerCase(),
      header: () => null,
      cell: () => null,
    },
    {
      id: 'report_type',
      header: 'Report',
      cell: ({ row }) => <span className="font-medium text-foreground">{REPORT_TYPE_LABEL[row.original.report_type as ReportType] ?? row.original.report_type}</span>,
    },
    {
      id: 'format',
      header: 'Format',
      cell: ({ row }) => <Badge variant={FORMAT_VARIANT[row.original.format]}>{REPORT_FORMAT_LABEL[row.original.format]}</Badge>,
    },
    {
      id: 'generated_by',
      header: 'Generated By',
      accessorFn: (row) => row.profiles?.full_name ?? '—',
    },
    {
      id: 'created_at',
      header: 'Date Generated',
      accessorFn: (row) => row.created_at,
      cell: ({ row }) => new Date(row.original.created_at).toLocaleString('en-PH', { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }),
    },
  ]

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="font-display text-xl font-semibold text-foreground">Reports & Export</h2>
          <p className="text-sm text-muted-foreground">Generate, preview, and export reports across every HR module.</p>
        </div>
        <Button onClick={() => navigate('/dashboard/reports/new')}>
          <Plus className="h-4 w-4" />
          Generate Report
        </Button>
      </div>

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
        <StatCard label="Total Reports Generated" value={stats?.total ?? 0} icon={FileBarChart} isLoading={statsLoading} index={0} />
        <StatCard label="Recruitment Reports" value={stats?.recruitment ?? 0} icon={Briefcase} isLoading={statsLoading} index={1} />
        <StatCard label="Employee Reports" value={stats?.employee ?? 0} icon={Users} isLoading={statsLoading} index={2} />
        <StatCard label="Payroll Reports" value={stats?.payroll ?? 0} icon={Wallet} isLoading={statsLoading} index={3} />
        <StatCard label="Attendance Reports" value={stats?.attendance ?? 0} icon={CalendarClock} isLoading={statsLoading} index={4} />
        <StatCard label="Leave Reports" value={stats?.leave ?? 0} icon={CalendarCheck} isLoading={statsLoading} index={5} />
      </div>

      <div>
        <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-muted-foreground">Export History</h3>
        <DataTable
          columns={columns}
          data={rows}
          isLoading={historyLoading}
          density="compact"
          searchPlaceholder="Search by report or generated by..."
          searchColumn="_searchText"
          emptyTitle="No reports generated yet"
          emptyDescription="Generate your first report to see its export history here."
          toolbarAction={
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder="Report Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={ALL_FILTER}>All report types</SelectItem>
                {(Object.entries(REPORT_TYPE_LABEL) as [ReportType, string][]).map(([value, label]) => (
                  <SelectItem key={value} value={value}>
                    {label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          }
        />
      </div>
    </div>
  )
}
